language: go
go:
  - 1.17

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

services:
  - docker

before_install:
  - go get -d golang.org/x/tools/cmd/cover
  - go get -d github.com/mattn/goveralls

script:
  - go get -d github.com/golang/mock/mockgen@v1.6.0
  - go install -v github.com/golang/mock/mockgen && export PATH=$GOPATH/bin:$PATH;
  - make test_rego_travis
  - go generate ./...
  - make test_build_travis
